version: "3.0"
services:
  app:
    build: .
    container_name: app
    entrypoint: /app/bin/entrypoint.sh
    restart: always
    ports:
      - "3000:3000"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_HOST=db"
      - "RAILS_ENV=production"
      - "NODE_ENV=production"
      - "POSTGRES_DB=test_cooking_production"
      - "MEMCACHED_URL=memcached:11211"
      - "BUNDLE_PATH=/usr/local/bundle"
      - "RAILS_SERVE_STATIC_FILES=true"
      - RAILS_MASTER_KEY
    depends_on:
      - db
      - memcached
    volumes:
      - bundle:/usr/local/bundle
  db:
    image: "postgres:12"
    container_name: db
    restart: always
    environment:
      - "POSTGRES_PASSWORD=password"

  memcached:
    image: "memcached:1.6.6"

volumes:
  bundle:
